name: GrokVoice
options:
  bundleIdPrefix: com.glebkalinin
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "15.0"
  createIntermediateGroups: true

settings:
  base:
    DEVELOPMENT_TEAM: ""
    CODE_SIGN_STYLE: Automatic
    SWIFT_VERSION: "5.9"
    MACOSX_DEPLOYMENT_TARGET: "14.0"

packages:
  LiveKit:
    url: https://github.com/livekit/client-sdk-swift.git
    from: "2.0.0"

targets:
  GrokVoice:
    type: application
    platform: macOS
    sources:
      - GrokVoice
    settings:
      base:
        INFOPLIST_FILE: GrokVoice/Resources/Info.plist
        CODE_SIGN_ENTITLEMENTS: GrokVoice/Resources/GrokVoice.entitlements
        PRODUCT_BUNDLE_IDENTIFIER: com.glebkalinin.GrokVoice
        PRODUCT_NAME: GrokVoice
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ENABLE_HARDENED_RUNTIME: YES
        COMBINE_HIDPI_IMAGES: YES
    dependencies:
      - package: LiveKit
    entitlements:
      path: GrokVoice/Resources/GrokVoice.entitlements
      properties:
        com.apple.security.device.audio-input: true
        com.apple.security.network.client: true
        com.apple.security.app-sandbox: true
